version: "3.9"

networks:
  app-net:
    driver: bridge

services:

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: lk-app
    ports:
      - "3000:3000"
    environment:
      LIVEKIT_URL: wss://livekit-server.volantislive.com
      LIVEKIT_API_KEY: APIY7KcSayArEyo
      LIVEKIT_API_SECRET: zewvscS0R9ieMngmHjf1ZuwHcmJeznzNeiC1wb556msA
      BIND_ADDR: "0.0.0.0:3000"
      RUST_LOG: info
    networks:
      - app-net
    restart: unless-stopped